import json
from datetime import datetime
import os

class ReportGenerator:
    
    def __init__(self):
        self.export_dir = 'exports'
        os.makedirs(self.export_dir, exist_ok=True)
    
    def generate_text_report(self, analysis_data):
        """Generate plain text report"""
        report = f"""
╔═══════════════════════════════════════════════════════════════════╗
║          GhostWriter Detector - Analysis Report                   ║
╚═══════════════════════════════════════════════════════════════════╝

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{"─" * 70}
AUTHENTICITY ASSESSMENT
{"─" * 70}

Human-like Score:     {analysis_data['human_score']}%
AI-assisted Score:    {analysis_data['ai_score']}%
Confidence Level:     {analysis_data['confidence']}%

{"─" * 70}
TEXT METRICS
{"─" * 70}

Word Count:           {analysis_data.get('word_count', 'N/A')}
Sentence Count:       {analysis_data.get('sentence_count', 'N/A')}
Avg Word Length:      {analysis_data.get('avg_word_length', 'N/A')} characters
Avg Sentence Length:  {analysis_data.get('avg_sentence_length', 'N/A')} words

{"─" * 70}
WRITING CHARACTERISTICS
{"─" * 70}

Vocabulary Score:         {analysis_data.get('vocabulary_score', 0)}/100
Sentence Complexity:      {analysis_data.get('sentence_complexity', 0)}/100
Readability Score:        {analysis_data.get('readability_score', 0)}/100
Emotional Variation:      {analysis_data.get('emotional_variation', 0)}/100
Repetition Score:         {analysis_data.get('repetition_score', 0)}/100
Formality Score:          {analysis_data.get('formality_score', 0)}/100

{"─" * 70}
ANALYSIS SUMMARY
{"─" * 70}

{self._get_summary(analysis_data)}

{"─" * 70}

Report generated by GhostWriter Detector
Visit: https://ghostwriter-detector.railway.app
"""
        return report
    
    def save_json_report(self, analysis_data, analysis_id):
        """Save analysis as JSON"""
        filename = f'report_{analysis_id}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.json'
        filepath = os.path.join(self.export_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(analysis_data, f, indent=2, default=str)
        
        return filepath
    
    def save_text_report(self, analysis_data, analysis_id):
        """Save analysis as text file"""
        report_text = self.generate_text_report(analysis_data)
        filename = f'report_{analysis_id}_{datetime.now().strftime("%Y%m%d_%H%M%S")}.txt'
        filepath = os.path.join(self.export_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report_text)
        
        return filepath
    
    def _get_summary(self, data):
        """Generate summary based on analysis"""
        human = data['human_score']
        ai = data['ai_score']
        
        if human > 70:
            summary = "This text appears to be written by a human. It shows natural variation in writing style, good vocabulary diversity, and consistent emotional patterns."
        elif human > 50:
            summary = "This text appears to be mostly human-written with some elements that could suggest AI assistance. The writing is generally natural but has some patterns that could indicate automated generation."
        elif human > 30:
            summary = "This text shows significant signs of AI involvement or assistance. While readable, it lacks the natural variation and emotional depth of pure human writing."
        else:
            summary = "This text appears to be heavily AI-generated or assisted. It shows strong indicators of template-based or automated generation with limited natural variation."
        
        return summary
